### ISSUE TITLE
Queries are not being deduped

### ISSUE THREAD

**Issue by davbrito** [ardeora/astro-tanstack-lwj#1]
On the https://lwj.aryandeora.com/pokedex-complete , whenever you click on next it fetches several times the same endpoint
![image](https://user-images.githubusercontent.com/39559632/223433787-11d82396-6812-436a-aa70-760e25a16cc1.png)

**Comment by ardeora** [comment]
Thanks for creating the issue! Yeah that was because the queries weren't correctly optimized because the pokemon API is a REST endpoint so it had to make multiple roundtrips to get the desired data. I have since then fixed the issue and you should not see anymore of the same queries being fired

**Comment by ardeora** [comment]
![Screenshot 2023-03-07 at 11 38 01 AM](https://user-images.githubusercontent.com/45807386/223488445-8d1f8f70-7ca9-4332-aa89-56207ac50d54.png)
